version: '3.8'

services:
  nginx:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge
